name: edubot
description: AI Homework Helper for Parents

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animation
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  lottie: ^2.6.0
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.0
  
  # Navigation
  go_router: ^12.1.1
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  http: ^1.2.1
  
  # AI & OCR
  google_ml_kit: ^0.18.0
  camera: ^0.10.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  
  # Audio
  flutter_tts: ^3.8.3
  speech_to_text: ^6.3.0
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  
  # Icons & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/patterns/
    - assets/animations/
    - assets/icons/
    - .env
