// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3yKIPHV4ATQN-Z8laQzWXFwe1w31mq4w',
    appId: '1:769088210742:web:edubot',
    messagingSenderId: '769088210742',
    projectId: 'edubot-3a646',
    authDomain: 'edubot-3a646.firebaseapp.com',
    storageBucket: 'edubot-3a646.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3yKIPHV4ATQN-Z8laQzWXFwe1w31mq4w',
    appId: '1:769088210742:android:56dbb019eeb65a89329597',
    messagingSenderId: '769088210742',
    projectId: 'edubot-3a646',
    storageBucket: 'edubot-3a646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3yKIPHV4ATQN-Z8laQzWXFwe1w31mq4w',
    appId: '1:769088210742:ios:edubot',
    messagingSenderId: '769088210742',
    projectId: 'edubot-3a646',
    storageBucket: 'edubot-3a646.firebasestorage.app',
    iosBundleId: 'com.edubot.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3yKIPHV4ATQN-Z8laQzWXFwe1w31mq4w',
    appId: '1:769088210742:ios:edubot',
    messagingSenderId: '769088210742',
    projectId: 'edubot-3a646',
    storageBucket: 'edubot-3a646.firebasestorage.app',
    iosBundleId: 'com.edubot.app',
  );
}
